import Header from "@/components/shared/Header";
import Navbar from "@/components/shared/Navbar";
import { Montserrat, Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
	variable: "--poppins-font",
	subsets: ["latin"],
	weight: ["400", "500", "600", "700"],
});

export const montserrat = Montserrat({
	variable: "--montserrat-font",
	subsets: ["latin"],
	weight: ["400", "500", "600", "700"],
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html data-theme="light" lang="en" className={`h-full antialiased`}>
			<body className={`${poppins.className} min-h-full flex flex-col`}>
				{/* <Header></Header>
				<Navbar></Navbar> */}
				{children}
			</body>
		</html>
	);
}
